routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Agendei\AgendeiController@agendei');
Route::post('/', 'Agendei\AgendeiController@agendei');

Route::get('/menuprincipal', 'Agendei\AgendeiController@menuprincipal');
Route::post('/menuprincipal', 'Agendei\AgendeiController@menuprincipal');

Route::resource('/funcionario', 'Agendei\FuncionarioController');
Route::get('/funcionario/inclusao', 'Agendei\FuncionarioController@cadastrofuncionario');
Route::post('/funcionario/inclusao', 'Agendei\FuncionarioController@cadastrofuncionario');
Route::post('/funcionario/edit{id}', [FuncionarioController::class, 'edit'])->name('funcionarios.edit');
Route::put('/funcionario/{id}', [FuncionarioController::class, 'update'])->name('funcionarios.update');

Route::resource('/recurso', 'Agendei\RecursoController');
Route::get('/recurso/inclusao', 'Agendei\RecursoController@cadastro_recurso');
Route::post('/recurso/inclusao', 'Agendei\RecursoController@cadastro_recurso');
Route::post('/recurso/edit{id}', [RecursoController::class, 'edit'])->name('recursos.edit');
Route::put('/recurso/{id}', [RecursoController::class, 'update'])->name('recursos.update');

Route::resource ('/agendamento', 'Agendei\AgendamentoController');
Route::get('/agendamento/inclusao', 'Agendei\AgendamentoController@cadastroagendamento');
Route::post('/agendamento/inclusao', 'Agendei\AgendamentoController@cadastroagendamento');
Route::post('/agendamento/edit{id}', [AgendamentoController::class, 'edit'])->name('agendamentos.edit');
Route::put('/agendamento/{id}', [AgendamentoController::class, 'update'])->name('agendamentos.update');

app/Funcionario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    //dados que o usuario pode inserir
    protected $fillable = ['nome', 'CPF', 'email', 'telefone', 'login', 'senha', 'tipo', 'status'];

}

app/Http/Controllers/Agendei/AgendamentoController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Agendamento;
use App\Http\Requests\AgendamentoFormRequest;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class AgendamentoController extends Controller
{
    private $agendamento;

    public function __construct(Agendamento $agendamento)
    {
        $this->agendamento = $agendamento;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Agendamento $agendamento)
    {
        $agendamentos = $this->agendamento->all();
        return view('Agendei.Agendamento.inicio_agendamento', compact('agendamentos'));
    }

    public function cadastroagendamento() {
        return view('Agendei.Agendamento.cadastro_agendamento');
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['programado', 'ativo', 'inativo', 'cancelado'];


        return View('agendei.agendamento.cadastro_agendamento', compact('statuss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AgendamentoFormRequest $request)
    {
        //traz todos os dados do formulario
      $Form_addagend = $request->except('_token');

      //insere dados na tabela recurso
       $insert = $this->agendamento->create($Form_addagend);

       if ($insert)
           return redirect()->route('agendamento.index');
       else
           return redirect()->back('agendamento.create');

       //valida os dados
       $this->validate($request, $this->agendamento->rules);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera o cadastro pelo id

        //$agendamento = $this->agendamento->find($id);

        $statuss = ['programado', 'ativo', 'inativo', 'cancelado'];

        if (!$agendamento = Agendamento::find($id)) {
            return redirect()->back();
        }

        return View('agendei.agendamento.edita_agendamento', compact(['statuss', 'agendamento']));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AgendamentoFormRequest $request, $id)
    {
        if (!$agendamento = Agendamento::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o agendamento : {$agendamento->id}");
        $agendamento->update($request->all());
        return redirect()->route('agendamento.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Agendei/AgendeiController.php
<?php

namespace App\Http\Controllers\Agendei;

use App\Funcionario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Http\Requests\LoginRequest;

class AgendeiController extends Controller
{
    /*public function __construct()
    {
        $this->middleware('auth')
            ->only ('menuprincipal');
    }
*/
    public function agendei()
    {
        return view('Agendei.Home.agendei');
    }

    public function menuprincipal()
    {
        return view('Agendei.Home.menu_principal');
    }

    public function Login()
    {
        return view('Agendei.Home.agendei');
    }

    public function validausuario(LoginRequest $request)
    {
        //Validações:
        $request->validated();

        //Verifica Login
        $usuario = trim($request->input('login'));
        $senha = trim($request->input('senha'));

        $usuario = Funcionario::where('login', $usuario)->first();

        //Verifica se existe usuario
        if (!$usuario) {
            echo ("Errro");
            return;
        }

        //Verifica senha
        if (!Hash::check($senha, $usuario->senha)) {
            echo ("Err0rr");
            return view('Agendei.Home.agendei');
        }

        //criar sessão
        echo ("Sessão Iniciada");
    }
}

app/Http/Controllers/Agendei/FuncionarioController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Funcionario;
use App\Http\Requests\FuncionarioFormRequest;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class FuncionarioController extends Controller
{
    private $funcionario;

    public function __construct(Funcionario $funcionario)
    {
        $this->funcionario = $funcionario;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Funcionario $funcionario)
    {
        $funcionarios = $this->funcionario->all();


        return view('agendei.funcionario.inicio_funcionario', compact('funcionarios'));
    }

    public function cadastrofuncionario()
    {
        return view('agendei.funcionario.cadastro_funcionario');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['ativo', 'inativo', 'suspenso'];
        $tipos = ['funcionario', 'professor', 'coordenador'];

        return View('agendei.funcionario.cadastro_funcionario', compact(['statuss','tipos']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FuncionarioFormRequest $request)
    {
      //traz todos os dados do formulario
      $Form_addfunc = $request->except('_token');

      //insere dados na tabela recurso
       $insert = $this->funcionario->create($Form_addfunc);

       if ($insert)
           return redirect()->route('funcionario.index');
       else
           return redirect()->back('funcionario.create');

       //valida os dados
       $this->validate($request, $this->funcionario->rules);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera o cadastro pelo id

        //$funcionario = $this->funcionario->find($id);


        $statuss = ['ativo', 'inativo', 'suspenso'];
        $tipos = ['funcionario', 'professor', 'coordenador'];

        if (!$funcionario = Funcionario::find($id)) {
            return redirect()->back();
        }
        return View('agendei.funcionario.edita_funcionario', compact(['statuss', 'tipos', 'funcionario']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FuncionarioFormRequest $request, $id)
    {
        if (!$funcionario = Funcionario::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o funcionario : {$funcionario->id}");
        $funcionario->update($request->all());
        return redirect()->route('funcionario.index');


           /*valida os dados*/
        $this->validate($request, $this->funcionario->rules);
      }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Agendei/RecursoController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\RecursoFormRequest;
use App\Recurso;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class RecursoController extends Controller
{
    private $recurso;

    public function __construct(Recurso $recurso)
    {
        $this->recurso = $recurso;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Recurso $recurso)
    {
        $recursos = $this->recurso->all();

        return view('agendei.recurso.inicio_recurso', compact('recursos')) ;
    }
    public function cadastrorecurso() {
        return view('Agendei.Recurso.cadastro_recurso');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['ativo', 'inativo', 'manutencao'];

        return View('agendei.recurso.cadastro_recurso', compact('statuss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecursoFormRequest $request)
    {
        //traz todos os dados do formulario
       $Form_addrecurso = $request->except('_token');

       //insere dados na tabela recurso
        $insert = $this->recurso->create($Form_addrecurso);

        if ($insert)
            return redirect()->route('recurso.index');
        else
            return redirect()->back('recurso.create');

        //valida os dados
        $this->validate($request, $this->recurso->rules);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera os dados da pesquisa pelo id
        //$recurso = $this->recurso->find($id);

        $titulo = 'Cadastro Novo Recurso';
        $statuss = ['ativo', 'inativo', 'manutencao'];

        if (!$recurso = Recurso::find($id)) {
            return redirect()->back();
        }
        return View('agendei.recurso.edita_recurso', compact(['titulo', 'statuss', 'recurso']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RecursoFormRequest $request, $id)
    {
        if (!$recurso = Recurso::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o recurso : {$recurso->id}");
        $recurso->update($request->all());
        return redirect()->route('recurso.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

app/Http/Controllers/Agendei/RelatorioController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class RelatorioController extends Controller
{
    //
}

resources/views/Agendei/Funcionario/cadastro_funcionario.blade.php
<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <link href="{{ asset('css/stilo.css') }}" rel="stylesheet">
        <title>cadastros de funcionario</title>
    </head>

<ul>
    <div class="tell">
        <label class="r">Tela de Cadastro</label>
        <a class="ui" href="{{ url('/funcionario') }}">voltar</a>
    </div>
</ul>

    <body id="fund">

@if(isset ($errors) && count($errors) > 0 )
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{$error}}</p>
        @endforeach
    </div>
@endif

<form  method="post" action={{route('funcionario.store')}}>
            @csrf

                <div class="registroformulario">Formulario de cadastro</div>
             <div class="telcard">
                <div class="ar6">
                <label class="non1"> Nome</label><br>
                <input class="non" type="text" name="nome" placeholder="digite seu nome " value="{{old('nome')}}"><br>
                </div>

                <div class="ar5">
                <label class="cp1" > CPF</label><br>
                <input class="cp" type="number" name="CPF"  placeholder="Digite seu cpf" value="{{old('CPF')}}"><br>
                </div>

                <div class="ar4">
                <label > Email</label><br>
                <input class="eml" type="text" name="email" placeholder="digite seu email" value="{{old('email')}}"><br>
                </div>

                <div class="ar3">
                <label class="telf1" > Telefone</label><br>
                <input class="telf" type="number" name="telefone" placeholder="digite seu telefone" value="{{old('telefone')}}"><br>
                </div>

                <div class="ar2">
                <label class="ltlogin1" >Login</label><br>
                <input class="ltlogin" type="text"name="login" placeholder="digite seu login" value="{{old('login')}}"><br>
                </div>

                <div class="ar">
                 <label class="ltsenha1">Senha</label><br>
                 <input class="ltsenha" type="password"  name="senha" placeholder="digite sua senha " value="{{old('senha')}}"><br><br>
                </div>

                <div class="nometipo">

                    <select name="tipo">
                    <option >Escolha o tipo:</option>
                        @foreach($tipos as $tipo)
                    <option value="{{$tipo}}"
                    @if( isset($funcionario) && $funcionario->tipo == $tipo)
                            selected;
                        @endif
                        >{{$tipo}}</option>
                    @endforeach
                </select>

                <select name="status">
                    <option>Escolha o status do funcionario:</option>
                        @foreach($statuss as $status)
                    <option value="{{$status}}"
                    @if( isset($funcionario) && $funcionario->status == $status)
                            selected
                        @endif
                    >{{$status}}</option>
                    @endforeach
                </select>

            </div>
            <div class="grav">
                <input  class="gravar" type="submit" value="Gravar">
            </div>
            </div>


        </form>
    </body>
</html>

resources/views/Agendei/Funcionario/edita_funcionario.blade.php
<!DOCTYPE html>

<html lang="pt-br">
    <head>

        <meta charset="utf-8">
            <link href="{{ asset('css/stilo.css') }}" rel="stylesheet">
    </head>
    <body>

        <ul>
            <div class="tell">

                <label class="r">editar</label>
                <a class="ui" href="{{ url('/funcionario') }}">voltar</a>
            </div>
        </ul>

@if(isset ($errors) && count($errors) > 0 )
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{$error}}</p>
        @endforeach
    </div>
@endif

<form method="post" action="{{route('funcionario.update', $funcionario->id)}}">
            @csrf
            @method('put')

                <div class="registroformulario">Formulario de editar</div>
         <div class="telcard">

            <div class="ar6">
                <label class="an1"> Nome </label><br>
                <input class="an"type="text" name="nome" value="{{$funcionario->nome or old('nome')}}"><br>
                 </div>

                <div class="ar5">
                <label class="acp1">CPF</label><br>
                <input class="acp" type="number" name="CPF" value="{{$funcionario->CPF or old('CPF')}}"><br>
                </div>

                <div class="ar4">
                <label class="am1">Email</label><br>
                <input class="am" type="text" name="email" value="{{$funcionario->email or old('email')}}"><br>
                </div>

                <div class="ar3">
                <label class="at1"> Telefone</label><br>
                <input class="at" type="number" name="telefone" value="{{$funcionario->telefone or old('telefone')}}"><br>
                </div>

                <div class="ar2">
                <label class="al1">Login</label><br>
                <input class="al" type="text" name="login" value="{{$funcionario->login or old('login')}}"><br>
                </div>

                <div class="ar">
                <label class="as1"> Senha</label><br>
                <input class="as" type="password" name="senha" value="{{$funcionario->senha or old('senha')}}"><br><br>
                </div>

                <div class="bott2">

                    <select name="tipo">
                    <option>Escolha o tipo:</option>
                        @foreach($tipos as $tipo)
                    <option value="{{$tipo}}"
                    @if( isset($funcionario) && $funcionario->tipo == $tipo)
                            selected;
                        @endif
                        >{{$tipo}}</option>
                    @endforeach
                </select>
                <select name="status">
                    <option>Escolha o status do funcionario:</option>
                        @foreach($statuss as $status)
                    <option value="{{$status}}"
                    @if( isset($funcionario) && $funcionario->status == $status)
                            selected
                        @endif
                    >{{$status}}</option>
                    @endforeach
                </select>
                </div>

               <div class="grav">
                <input class="gravar" type="submit" value="Gravar">
               </div>
        </form>
    </body>
</html>

resources/views/Agendei/Funcionario/inicio_funcionario.blade.php
<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Funcionarios</title>
        <link href="{{ asset('css/stilo.css') }}" rel="stylesheet">
    </head>
    <body id="fund">


<ul>
<div class="divfui">
        <label class="ff">funcionario</label>
        <a class="volt" href="{{ url('/menuprincipal') }}">Voltar</a>
        <a class="cadast" href="{{route('funcionario.create')}}" role="button">Cadastrar</a>

    </div>
</ul>


 <div class="tab">
         <table class="tabelas1">
        <tr>

            <th class="id1">ID</th>
            <th class="nome1">NOME</th>
            <th class="cpf1">CPF</th>
            <th class="telefone1">TELEFONE</th>
            <th class="email1">EMAIL</th>
            <th class="tipo1">TIPO</th>
            <th class="status1">STATUS</th>
            <th class="acao1">AÇÃO</th>

        </tr>
    </div>

         @foreach($funcionarios as $funcionario)

         <tr>

            <td class="id1">{{$funcionario->id}}</td>
            <td class="nome1">{{$funcionario->nome}}</td>
            <td class="cpf1">{{$funcionario->CPF}}</td>
            <td class="telefone1">{{$funcionario->telefone}}</td>
            <td class="email1">{{$funcionario->email}}</td>
            <td  class="tipo1">{{$funcionario->tipo}}</td>
            <td class="status1">{{$funcionario->status}}</td>
            <td>
                <a class="ac" href="{{route('funcionario.edit', $funcionario->id)}}" role="button"><?php include "img/editar.svg";?></a>
            </td>
        </tr>
        @endforeach
    </table>

    @php
    $db = mysqli_connect("localhost","root","mysql123","agendei");
    @endphp

    </body>
</html>