routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Agendei\AgendeiController@agendei');
Route::post('/', 'Agendei\AgendeiController@agendei');

Route::get('/menuprincipal', 'Agendei\AgendeiController@menuprincipal');
Route::post('/menuprincipal', 'Agendei\AgendeiController@menuprincipal');

Route::resource('/funcionario', 'Agendei\FuncionarioController');
Route::get('/funcionario/inclusao', 'Agendei\FuncionarioController@cadastrofuncionario');
Route::post('/funcionario/inclusao', 'Agendei\FuncionarioController@cadastrofuncionario');
Route::post('/funcionario/edit{id}', [FuncionarioController::class, 'edit'])->name('funcionarios.edit');
Route::put('/funcionario/{id}', [FuncionarioController::class, 'update'])->name('funcionarios.update');

Route::resource('/recurso', 'Agendei\RecursoController');
Route::get('/recurso/inclusao', 'Agendei\RecursoController@cadastro_recurso');
Route::post('/recurso/inclusao', 'Agendei\RecursoController@cadastro_recurso');
Route::post('/recurso/edit{id}', [RecursoController::class, 'edit'])->name('recursos.edit');
Route::put('/recurso/{id}', [RecursoController::class, 'update'])->name('recursos.update');

Route::resource ('/agendamento', 'Agendei\AgendamentoController');
Route::get('/agendamento/inclusao', 'Agendei\AgendamentoController@cadastroagendamento');
Route::post('/agendamento/inclusao', 'Agendei\AgendamentoController@cadastroagendamento');
Route::post('/agendamento/edit{id}', [AgendamentoController::class, 'edit'])->name('agendamentos.edit');
Route::put('/agendamento/{id}', [AgendamentoController::class, 'update'])->name('agendamentos.update');

app/Recurso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recurso extends Model
{
    //dados que o usuario pode inserir
    protected $fillable = ['nome', 'descricao', 'sigla', 'status'];

}

app/Http/Controllers/Agendei/AgendamentoController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Agendamento;
use App\Http\Requests\AgendamentoFormRequest;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class AgendamentoController extends Controller
{
    private $agendamento;

    public function __construct(Agendamento $agendamento)
    {
        $this->agendamento = $agendamento;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Agendamento $agendamento)
    {
        $agendamentos = $this->agendamento->all();
        return view('Agendei.Agendamento.inicio_agendamento', compact('agendamentos'));
    }

    public function cadastroagendamento() {
        return view('Agendei.Agendamento.cadastro_agendamento');
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['programado', 'ativo', 'inativo', 'cancelado'];


        return View('agendei.agendamento.cadastro_agendamento', compact('statuss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AgendamentoFormRequest $request)
    {
        //traz todos os dados do formulario
      $Form_addagend = $request->except('_token');

      //insere dados na tabela recurso
       $insert = $this->agendamento->create($Form_addagend);

       if ($insert)
           return redirect()->route('agendamento.index');
       else
           return redirect()->back('agendamento.create');

       //valida os dados
       $this->validate($request, $this->agendamento->rules);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera o cadastro pelo id

        //$agendamento = $this->agendamento->find($id);

        $statuss = ['programado', 'ativo', 'inativo', 'cancelado'];

        if (!$agendamento = Agendamento::find($id)) {
            return redirect()->back();
        }

        return View('agendei.agendamento.edita_agendamento', compact(['statuss', 'agendamento']));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AgendamentoFormRequest $request, $id)
    {
        if (!$agendamento = Agendamento::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o agendamento : {$agendamento->id}");
        $agendamento->update($request->all());
        return redirect()->route('agendamento.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Agendei/AgendeiController.php
<?php

namespace App\Http\Controllers\Agendei;

use App\Funcionario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Http\Requests\LoginRequest;

class AgendeiController extends Controller
{
    /*public function __construct()
    {
        $this->middleware('auth')
            ->only ('menuprincipal');
    }
*/
    public function agendei()
    {
        return view('Agendei.Home.agendei');
    }

    public function menuprincipal()
    {
        return view('Agendei.Home.menu_principal');
    }

    public function Login()
    {
        return view('Agendei.Home.agendei');
    }

    public function validausuario(LoginRequest $request)
    {
        //Validações:
        $request->validated();

        //Verifica Login
        $usuario = trim($request->input('login'));
        $senha = trim($request->input('senha'));

        $usuario = Funcionario::where('login', $usuario)->first();

        //Verifica se existe usuario
        if (!$usuario) {
            echo ("Errro");
            return;
        }

        //Verifica senha
        if (!Hash::check($senha, $usuario->senha)) {
            echo ("Err0rr");
            return view('Agendei.Home.agendei');
        }

        //criar sessão
        echo ("Sessão Iniciada");
    }
}

app/Http/Controllers/Agendei/FuncionarioController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Funcionario;
use App\Http\Requests\FuncionarioFormRequest;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class FuncionarioController extends Controller
{
    private $funcionario;

    public function __construct(Funcionario $funcionario)
    {
        $this->funcionario = $funcionario;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Funcionario $funcionario)
    {
        $funcionarios = $this->funcionario->all();


        return view('agendei.funcionario.inicio_funcionario', compact('funcionarios'));
    }

    public function cadastrofuncionario()
    {
        return view('agendei.funcionario.cadastro_funcionario');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['ativo', 'inativo', 'suspenso'];
        $tipos = ['funcionario', 'professor', 'coordenador'];

        return View('agendei.funcionario.cadastro_funcionario', compact(['statuss','tipos']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FuncionarioFormRequest $request)
    {
      //traz todos os dados do formulario
      $Form_addfunc = $request->except('_token');

      //insere dados na tabela recurso
       $insert = $this->funcionario->create($Form_addfunc);

       if ($insert)
           return redirect()->route('funcionario.index');
       else
           return redirect()->back('funcionario.create');

       //valida os dados
       $this->validate($request, $this->funcionario->rules);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera o cadastro pelo id

        //$funcionario = $this->funcionario->find($id);


        $statuss = ['ativo', 'inativo', 'suspenso'];
        $tipos = ['funcionario', 'professor', 'coordenador'];

        if (!$funcionario = Funcionario::find($id)) {
            return redirect()->back();
        }
        return View('agendei.funcionario.edita_funcionario', compact(['statuss', 'tipos', 'funcionario']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FuncionarioFormRequest $request, $id)
    {
        if (!$funcionario = Funcionario::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o funcionario : {$funcionario->id}");
        $funcionario->update($request->all());
        return redirect()->route('funcionario.index');


           /*valida os dados*/
        $this->validate($request, $this->funcionario->rules);
      }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Agendei/RecursoController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\RecursoFormRequest;
use App\Recurso;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class RecursoController extends Controller
{
    private $recurso;

    public function __construct(Recurso $recurso)
    {
        $this->recurso = $recurso;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Recurso $recurso)
    {
        $recursos = $this->recurso->all();

        return view('agendei.recurso.inicio_recurso', compact('recursos')) ;
    }
    public function cadastrorecurso() {
        return view('Agendei.Recurso.cadastro_recurso');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuss = ['ativo', 'inativo', 'manutencao'];

        return View('agendei.recurso.cadastro_recurso', compact('statuss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecursoFormRequest $request)
    {
        //traz todos os dados do formulario
       $Form_addrecurso = $request->except('_token');

       //insere dados na tabela recurso
        $insert = $this->recurso->create($Form_addrecurso);

        if ($insert)
            return redirect()->route('recurso.index');
        else
            return redirect()->back('recurso.create');

        //valida os dados
        $this->validate($request, $this->recurso->rules);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //recupera os dados da pesquisa pelo id
        //$recurso = $this->recurso->find($id);

        $titulo = 'Cadastro Novo Recurso';
        $statuss = ['ativo', 'inativo', 'manutencao'];

        if (!$recurso = Recurso::find($id)) {
            return redirect()->back();
        }
        return View('agendei.recurso.edita_recurso', compact(['titulo', 'statuss', 'recurso']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RecursoFormRequest $request, $id)
    {
        if (!$recurso = Recurso::find($id)) {
            return redirect()->back();
        }

        //dd("Editando o recurso : {$recurso->id}");
        $recurso->update($request->all());
        return redirect()->route('recurso.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

app/Http/Controllers/Agendei/RelatorioController.php
<?php

namespace App\Http\Controllers\Agendei;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpKernel\Event\ViewEvent;

class RelatorioController extends Controller
{
    //
}

resources/views/Agendei/Recurso/cadastro_recurso.blade.php
<!DOCTYPE html>

<html lang="pt-br">
    <head>

        <meta charset="utf-8">
        <link href="{{ asset('css/stilo.css') }}" rel="stylesheet">
    </head>


{{--link das funções da rotina--}}
<ul>
    <div class="cart" >
        <label class="scrip"> Recurso </label>
        <a  class="phs" href="{{ url('/recurso') }}">Voltar</a>
    </div>
</ul>


    <body>

@if(isset ($errors) && count($errors) > 0 )
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{$error}}</p>
        @endforeach
    </div>
@endif

<form  method="post" action="{{route('recurso.store')}}">

                <div class="castr">cadastro recurso</div>
            @csrf
        <div class="cardrs">
            <div class="t1">
                 <label>Nome</label><br>
                <input class="p1" type="text" name="nome" required value='{{old('nomne')}}'><br>
            </div>

            <div class="t2">
                <label> Sigla</label><br>
                <input class="p2" type="text" name="sigla" required value='{{old('sigla')}}'><br>
            </div>

            <div class="t3">
                <label> Descrição Completa</label><br>
                <input class="p3" type="text" name="descricao"required value='{{old('descricao')}}'><br>
            </div>

                <div class="oi" >
                <select name="status">
                    <option>Escolha o status do recurso:</option>
                    @foreach($statuss as $status)
                    <option value="{{$status}}"
                    @if( isset($recurso) && $recurso->status == $status)
                    @endif>{{$status}}</option>
                    @endforeach
                </select>
            </div>
               <div class="rs">
                 <input class="rss" type="submit" value="Gravar">
              </div>
            </div>
        </form>
    </body>
</html>

resources/views/Agendei/Recurso/edita_recurso.blade.php
<h3> Cadastro Recurso </h3>

{{--link das funções da rotina--}}
<ul>
    <li>
        <a href="{{ url('/recurso') }}">Voltar</a>
    </li>
</ul>

<!DOCTYPE html>

<html lang="pt-br">
    <head>

        <meta charset="utf-8">
    </head>
    <body>

@if(isset ($errors) && count($errors) > 0 )
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{$error}}</p>
        @endforeach
    </div>
@endif

<form method="post" action="{{route('recurso.update', $recurso->id)}}">


            @csrf
            @method('put')

                Nome: <input type="text" name="nome" value='{{$recurso->nome or old('nomne')}}'><br><br>
                Sigla: <input type="text" name="sigla" value='{{$recurso->sigla or old('sigla')}}'><br><br>
                Descrição Completa: <input type="text" name="descricao" value='{{$recurso->descricao or old('descricao')}}'><br><br>

                <select name="status">
                    <option>Escolha o status do recurso:</option>
                    @foreach($statuss as $status)
                    <option>
                     value="{{$status}}"
                    @if( isset($recurso) && $recurso->status == $status)
                    @endif
                    {{$status}}</option>
                    @endforeach
                </select>

                <div style="text-align: right">
                <input type="submit" value="Gravar">
              </div>
            </p>
        </form>
    </body>
</html>

resources/views/Agendei/Recurso/inicio_recurso.blade.php
<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Recursos</title>
        <link href="{{ asset('css/stilo.css') }}" rel="stylesheet">
    </head>
    <body>

<ul>
    <div class="cart" >
        <label class="scrip">Recurso</label>
        <a class="js" href="{{route('recurso.create')}}" role="button">Cadastrar</a>
        <a  class="vue" href="{{ url('/menuprincipal') }}">Voltar</a>
    </div>


</ul><br><br>






    <table class=" tabelarecurso">
        <tr>
            <th>ID</th>
            <th>RECURSO</th>
            <th>SIGLA</th>
            <th>STATUS</th>
            <th >AÇÃO</th>
        </tr>
         @foreach($recursos as $recurso)
            <tr>
            <td class="status1">{{$recurso->id}}</td>
            <td class="status1">{{$recurso->nome}}</td>
            <td class="status1">{{$recurso->sigla}}</td>
            <td class="status1">{{$recurso->status}}</td>
            <td>
                <a  href="{{route('recurso.edit', $recurso->id)}}" role="button">editar</a>
            </td>
        </tr>
        @endforeach
    </table>

    @php
        $db = mysqli_connect("localhost","root","mysql123","agendei");

    @endphp

    </body>
</html>